# coding: utf-8
from sqlalchemy import Column, Date, PrimaryKeyConstraint, BigInteger, Integer, Numeric, Boolean, String, ForeignKey
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
metadata = Base.metadata


# class ZSECFORM13(Base):
#     __tablename__ = 'ZSECFORM13'
#     __table_args__ = ()

#     MANDT = Column(String)
#     ZACCESSIONNO = Column(String(20), primary_key=True)
#     ZSECDOC = Column(String)
#     ZSEC_ACCEPTTIME = Column(String(14))
#     ZCIK_ISSUER = Column(String)
#     ZFORM_TYPE = Column(String)
#     ZISSUER_SYMBOL = Column(String)		# needs consult
#     ZSECHEADER = Column(String)
#     ZDOC_COUNT = Column(Integer)
#     ZREPORT_PERIOD = Column(Date)
#     ZDATE_FILED = Column(Date)
#     ZDATE_CHANGED = Column(Date)
#     ZAMEND = Column(String)			# needs consult
#     ZAMEND_NUMBER = Column(Integer)		# needs consult
#     ZAMEND_RESTATE = Column(String)		# needs consult
#     ZAMEND_NEWHOLDING = Column(String)	# needs consult
#     VERSION = Column(String)			# needs consult
#     ZSEC_FILENO = Column(String)		
#     ZSEC_FILENAME = Column(String)		# needs consult
#     ZFILE_DESCRIP = Column(String)		# needs consult
#     ZXML_VERSION = Column(String)
#     ZSCHEMA_VERSION = Column(String)	# needs consult
#     ZSECTION16 = Column(String)		# needs consult
#     ZSIGN_TITLE = Column(String)
#     ZSIGN_NAME = Column(String)
#     ZSIGN_DATE = Column(Date)
#     ERDAT = Column(Date)			# needs consult
#     ERNAME = Column(String)			# needs consult
#     ZTOTAL_TABENTRY = Column(String)         
#     ZTOTAL_TABVALUE = Column(Integer)

# class ZSECFORM13_FILER(Base):
#     __tablename__ = 'ZSECFORM13_FILER'
#     __table_args__ = ()

#     MANDT = Column(String)
#     ZACCESSIONNO = Column(String(20), primary_key=True)
#     ZCIK_ISSUER = Column(String)
#     ZCOMPCONFDNAME = Column(String)
#     ZSEC_IRSNO = Column(String)
#     ZINCORP_STATE = Column(String)
#     ZFISCAL_YREND = Column(String)
#     BUS_STRAS = Column(String)
#     BUS_CITY = Column(String)
#     BUS_REGION = Column(String)
#     BUS_BEZEI20 = Column(String)
#     BUS_POST_CODE = Column(String)
#     BUS_TELF = Column(String)
#     MAIL_STRAS = Column(String)
#     MAIL_CITY = Column(String)
#     MAIL_REGION = Column(String)
#     MAIL_POST_CODE = Column(String)
#     ZFCOMPCONFDNAME1 = Column(String)
#     ZDATE_NAMECHANGE1 = Column(Date)
#     ZFCOMPCONFDNAME2 = Column(String)
#     ZDATE_NAMECHANGE2 = Column(Date)
#     ZFCOMPCONFDNAME3 = Column(String)
#     ZDATE_NAMECHANGE3 = Column(Date)


# class ZSECFORM13F_INFO(Base):
#     __tablename__ = 'ZSECFORM13F_INFO'
#     __table_args__ = (PrimaryKeyConstraint('ZACCESSIONNO', 'ZCIK_ISSUER', 'ZCUSIP', 'ZINVST_DISCRET'),)

#     MANDT = Column(String)
#     ZACCESSIONNO = Column(String(20), ForeignKey("ZSECFORM13.ZACCESSIONNO"))
#     ZCIK_ISSUER = Column(String)
#     ZCUSIP = Column(String)
#     ZSHAREPRINCIPAL = Column(String)
#     ZCOMPCONFDNAME = Column(String)
#     ZCLASS_TITLE = Column(String)
#     ZVALUE = Column(Numeric(precision=25, scale=2))
#     ZSHARES = Column(String)
#     ZSSHPRNAMTYPE = Column(String)
#     ZPUT_CALL = Column(String)
#     ZINVST_DISCRET = Column(String)
#     ZOTHERMANAGERS = Column(String)
#     ZVOTEAUTHSOLE = Column(Integer)
#     ZVOTEAUTHSHARED = Column(Integer)
#     ZVOTEAUTHNONE = Column(Integer)

class ZSECFORM3(Base):
    __tablename__ = 'ZSECFORM3'
    __table_args__ = ()

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20), primary_key=True)
    SEC_DOC = Column(String(40))
    ACCEPT_TIME = Column(String(14))
    CIK_ISSUER = Column(String(10))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10))
    SEC_HEADER = Column(String(40))
    DOC_FILE_COUNT = Column(Integer)
    REPORT_PERIOD = Column(Date)
    DATE_FILED = Column(Date)
    DATE_CHANGED = Column(Date)
    VERSION = Column(String(6))       
    FILENAME = Column(String(40))   
    FILEDESCRIP = Column(String(400))   
    XML_VERSION = Column(String(20))
    SCHEMA_VERSION = Column(String(10)) 
    SECTION_16 = Column(String(1))   
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)
    DERV_TAB = Column(Boolean)
    NDERV_TAB = Column(Boolean)
    FTNOTE_FLG = Column(Boolean)
    ERDAT = Column(Date)
    ERNAME = Column(String(12))

class ZSECFORM3_ISSUER(Base):
    __tablename__ = 'ZSECFORM3_ISSUER'
    __table_args__ = ()

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20), primary_key=True)
    CIK_ISSUER = Column(String(10))
    SEC_DOC = Column(String(40))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10)) 
    ISSU_CONFDNAME = Column(String(100))
    SIC = Column(String(10))
    IRS = Column(String(10))
    STATE_INCORP = Column(String(3))
    FISCAL_YEAREND = Column(String(4))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME1 = Column(String(100))
    DATE_NAMECHANGE1 = Column(Date)
    FCOMP_CONFORMEDNAME2 = Column(String(100))
    DATE_NAMECHANGE2 = Column(Date)
    FCOMP_CONFORMEDNAME3 = Column(String(100))
    DATE_NAMECHANGE3 = Column(Date)

class ZSECFORM3_REPTER(Base):
    __tablename__ = 'ZSECFORM3_REPTER'
    __table_args__ = ()

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20), primary_key=True)
    CIK_REPORTER = Column(String(10))
    SEC_DOC = Column(String(40))
    DATE_REPORT = Column(Date)
    FORM_TYPE = Column(String(10))
    REPT_CONFDNAME = Column(String(100))
    FIRST_NAME = Column(String(100))
    LAST_NAME = Column(String(100))
    MIDDLE_NAME = Column(String(100))
    OFFICER_TITLE = Column(String(100))
    SEC_ACT = Column(String(15))
    SEC_FILENO = Column(String(20))
    FILM_NO = Column(String(10))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME = Column(String(100))
    DATE_NAMECHANGE = Column(Date)
    DIRECTOR = Column(String(1))
    OFFICER = Column(String(1))
    TENPERCENTOWNER = Column(String(1))
    OTHER = Column(String(1))
    TEXT_OTHER = Column(String(40))
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)

class ZSECFORM3_DTAB(Base):
    __tablename__ = 'ZSECFORM3_DTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    ACCESS_TRANXID = Column(Integer)
    DERIVSECURITY_TYPETITLE = Column(String(100))
    DATE_EXCISE = Column(String(25))
    DATE_EXPIRE = Column(String(25))
    SECURITY_TYPETITLE = Column(String(100))
    SHARE_AMOUNT = Column(String(30))
    EXPRICE_DERVSECURTY = Column(String(30))
    OWNERSHIPTYPE = Column(String(1))
    INDBENF_OWNER = Column(String(100))

class ZSECFORM3_NDTAB(Base):
    __tablename__ = 'ZSECFORM3_NDTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    ACCESS_TRANXID = Column(Integer)
    FORM_TYPE = Column(String(10))
    SECURITY_TYPETITLE = Column(String(100))
    SECTITLE_FTNOTE = Column(String(100))
    SHARES = Column(String(30))
    SHARE_FTNOTE = Column(String(100))
    SHARE_VALUE = Column(String(30))
    SHAREVALUE_FTNOTE = Column(String(100))
    OWNERSHIPTYPE = Column(String(1))
    OWNSHIP_FTNOTE = Column(String(100))
    INDBENF_OWNER = Column(String(100))
    INDBENF_OWNER_FTNOTE = Column(String(100))

class ZSECFORM3_FTNOTE(Base):
    __tablename__ = 'ZSECFORM3_FTNOTE'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'FOOTNOTE_ID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    SEC_DOC = Column(String(40))
    FOOTNOTE_ID = Column(String(5))
    FOOTNOTE_TXT = Column(String)


class ZSECFORM4(Base):
    __tablename__ = 'ZSECFORM4'
    __table_args__ = ()

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20), primary_key=True)
    SEC_DOC = Column(String(40))
    ACCEPT_TIME = Column(String(14))
    CIK_ISSUER = Column(String(10))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10))
    SEC_HEADER = Column(String(40))
    DOC_FILE_COUNT = Column(Integer)
    REPORT_PERIOD = Column(Date)
    DATE_FILED = Column(Date)
    DATE_CHANGED = Column(Date)
    VERSION = Column(String(6))       
    FILENAME = Column(String(40))   
    FILEDESCRIP = Column(String(400))   
    XML_VERSION = Column(String(20))
    SCHEMA_VERSION = Column(String(10)) 
    SECTION_16 = Column(String(1))   
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)
    DERV_TAB = Column(Boolean)
    NDERV_TAB = Column(Boolean)
    FTNOTE_FLG = Column(Boolean)
    ERDAT = Column(Date)
    ERNAME = Column(String(12))

class ZSECFORM4_ISSUER(Base):
    __tablename__ = 'ZSECFORM4_ISSUER'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'CIK_ISSUER'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    CIK_ISSUER = Column(String(10))
    SEC_DOC = Column(String(40))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10)) 
    ISSU_CONFDNAME = Column(String(100))
    SIC = Column(String(10))
    IRS = Column(String(10))
    STATE_INCORP = Column(String(3))
    FISCAL_YEAREND = Column(String(4))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME1 = Column(String(100))
    DATE_NAMECHANGE1 = Column(Date)
    FCOMP_CONFORMEDNAME2 = Column(String(100))
    DATE_NAMECHANGE2 = Column(Date)
    FCOMP_CONFORMEDNAME3 = Column(String(100))
    DATE_NAMECHANGE3 = Column(Date)

class ZSECFORM4_REPTER(Base):
    __tablename__ = 'ZSECFORM4_REPTER'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'CIK_REPORTER'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    CIK_REPORTER = Column(String(10))
    SEC_DOC = Column(String(40))
    DATE_REPORT = Column(Date)
    FORM_TYPE = Column(String(10))
    REPT_CONFDNAME = Column(String(100))
    FIRST_NAME = Column(String(100))
    LAST_NAME = Column(String(100))
    MIDDLE_NAME = Column(String(100))
    OFFICER_TITLE = Column(String(100))
    SEC_ACT = Column(String(15))
    SEC_FILENO = Column(String(20))
    FILM_NO = Column(String(10))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME = Column(String(100))
    DATE_NAMECHANGE = Column(Date)
    DIRECTOR = Column(String(1))
    OFFICER = Column(String(1))
    TENPERCENTOWNER = Column(String(1))
    OTHER = Column(String(1))
    TEXT_OTHER = Column(String(40))
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)

class ZSECFORM4_DTAB(Base):
    __tablename__ = 'ZSECFORM4_DTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    DATE_TRANS = Column(Date)
    DATE_EXECUTION = Column(Date)
    TRANS_CODE = Column(String(1))
    FORM_TYPE = Column(String(10))
    ACCESS_TRANXID = Column(Integer)
    SWAP = Column(String(1))
    ACQ_DISPOSED = Column(String(1))
    DERIVSECURITY_TYPETITLE = Column(String(100))
    DATE_EXCISE = Column(String(25))
    DATE_EXPIRE = Column(String(25))
    SECURITY_TYPETITLE = Column(String(100))
    SHARE_AMOUNT = Column(String(30))
    EXPRICE_DERVSECURTY = Column(String(30))
    PRICE_DERIV = Column(String(20))
    SHARES_AFTER = Column(String(30))
    OWNERSHIPTYPE = Column(String(1))
    INDBENF_OWNER = Column(String(100))

class ZSECFORM4_NDTAB(Base):
    __tablename__ = 'ZSECFORM4_NDTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    ACCESS_TRANXID = Column(Integer)
    DATE_TRANS = Column(Date)
    DATE_EXECUTION = Column(Date)
    TRANS_CODE = Column(String(1))
    TRANSCODE_FTNOTE = Column(String(100))
    FORM_TYPE = Column(String(10))
    SECURITY_TYPETITLE = Column(String(100))
    SECTITLE_FTNOTE = Column(String(100))
    SWAP = Column(String(1))
    SHARES = Column(String(30))
    SHARE_FTNOTE = Column(String(100))
    ACQ_DISPOSED = Column(String(1))
    SHARE_VALUE = Column(String(30))
    SHAREVALUE_FTNOTE = Column(String(100))
    SHARES_AFTER = Column(String(30))
    SHAREAFT_FTNOTE = Column(String(100))
    OWNERSHIPTYPE = Column(String(1))
    OWNSHIP_FTNOTE = Column(String(100))
    INDBENF_OWNER = Column(String(100))
    INDBENF_OWNER_FTNOTE = Column(String(100))



class ZSECFORM4_FTNOTE(Base):
    __tablename__ = 'ZSECFORM4_FTNOTE'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'FOOTNOTE_ID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    SEC_DOC = Column(String(40))
    FOOTNOTE_ID = Column(String(5))
    FOOTNOTE_TXT = Column(String)

class ZSECFORM5(Base):
    __tablename__ = 'ZSECFORM5'
    __table_args__ = ()

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20), primary_key=True)
    SEC_DOC = Column(String(40))
    ACCEPT_TIME = Column(String(14))
    CIK_ISSUER = Column(String(10))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10))
    SEC_HEADER = Column(String(40))
    DOC_FILE_COUNT = Column(Integer)
    REPORT_PERIOD = Column(Date)
    DATE_FILED = Column(Date)
    DATE_CHANGED = Column(Date)
    VERSION = Column(String(6))       
    FILENAME = Column(String(40))   
    FILEDESCRIP = Column(String(400))   
    XML_VERSION = Column(String(20))
    SCHEMA_VERSION = Column(String(10)) 
    SECTION_16 = Column(String(1))
    FORM3HOLDRPTD = Column(String(1))
    FORM4TRANXRPTD = Column(String(1))
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)
    DERV_TAB = Column(Boolean)
    NDERV_TAB = Column(Boolean)
    FTNOTE_FLG = Column(Boolean)
    ERDAT = Column(Date)

class ZSECFORM5_ISSUER(Base):
    __tablename__ = 'ZSECFORM5_ISSUER'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'CIK_ISSUER'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    CIK_ISSUER = Column(String(10))
    SEC_DOC = Column(String(40))
    FORM_TYPE = Column(String(10))
    ISSUER_SYMBOL = Column(String(10)) 
    ISSU_CONFDNAME = Column(String(100))
    SIC = Column(String(10))
    IRS = Column(String(10))
    STATE_INCORP = Column(String(3))
    FISCAL_YEAREND = Column(String(4))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME1 = Column(String(100))
    DATE_NAMECHANGE1 = Column(Date)
    FCOMP_CONFORMEDNAME2 = Column(String(100))
    DATE_NAMECHANGE2 = Column(Date)
    FCOMP_CONFORMEDNAME3 = Column(String(100))
    DATE_NAMECHANGE3 = Column(Date)

class ZSECFORM5_REPTER(Base):
    __tablename__ = 'ZSECFORM5_REPTER'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'CIK_REPORTER'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    CIK_REPORTER = Column(String(10))
    SEC_DOC = Column(String(40))
    DATE_REPORT = Column(Date)
    FORM_TYPE = Column(String(10))
    REPT_CONFDNAME = Column(String(100))
    FIRST_NAME = Column(String(100))
    LAST_NAME = Column(String(100))
    MIDDLE_NAME = Column(String(100))
    OFFICER_TITLE = Column(String(100))
    SEC_ACT = Column(String(15))
    SEC_FILENO = Column(String(20))
    FILM_NO = Column(String(10))
    BUS_STREET1 = Column(String(100))
    BUS_STREET2 = Column(String(100))
    BUS_CITY  = Column(String(50))
    BUS_STATE = Column(String(3))
    BUS_STATETXT = Column(String(100))
    BUS_ZIPCODE = Column(String(10))
    BUS_PHONE = Column(String(16))
    MAIL_STREET1 = Column(String(100))
    MAIL_STREET2 = Column(String(100))
    MAIL_CITY = Column(String(50))
    MAIL_STATE = Column(String(3))
    MAIL_STATETXT = Column(String(100))
    MAIL_ZIPCODE = Column(String(10))
    FCOMP_CONFORMEDNAME = Column(String(100))
    DATE_NAMECHANGE = Column(Date)
    DIRECTOR = Column(String(1))
    OFFICER = Column(String(1))
    TENPERCENTOWNER = Column(String(1))
    OTHER = Column(String(1))
    TEXT_OTHER = Column(String(40))
    SIGN_TITLE = Column(String(400))
    SIGN_NAME = Column(String(400))
    SIGN_DATE = Column(Date)

class ZSECFORM5_DTAB(Base):
    __tablename__ = 'ZSECFORM5_DTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    DATE_TRANS = Column(Date)
    DATE_EXECUTION = Column(Date)
    TRANS_CODE = Column(String(1))
    FORM_TYPE = Column(String(10))
    ACCESS_TRANXID = Column(Integer)
    SWAP = Column(String(1))
    ACQ_DISPOSED = Column(String(1))
    DERIVSECURITY_TYPETITLE = Column(String(100))
    DATE_EXCISE = Column(String(25))
    DATE_EXPIRE = Column(String(25))
    SECURITY_TYPETITLE = Column(String(100))
    SHARE_AMOUNT = Column(String(30))
    EXPRICE_DERVSECURTY = Column(String(30))
    PRICE_DERIV = Column(String(20))
    SHARES_AFTER = Column(String(30))
    OWNERSHIPTYPE = Column(String(1))
    INDBENF_OWNER = Column(String(100))

class ZSECFORM5_NDTAB(Base):
    __tablename__ = 'ZSECFORM5_NDTAB'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'ACCESS_TRANXID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    ACCESS_TRANXID = Column(Integer)
    DATE_TRANS = Column(Date)
    TRANSDATE_FTNOTE = Column(String(30))
    DATE_EXECUTION = Column(Date)
    TRANS_CODE = Column(String(1))
    TRANSCODE_FTNOTE = Column(String(100))
    FORM_TYPE = Column(String(10))
    SECURITY_TYPETITLE = Column(String(100))
    SECTITLE_FTNOTE = Column(String(100))
    SWAP = Column(String(1))
    SWAP_FTNOTE = Column(String(30))
    SHARES = Column(String(30))
    SHARE_FTNOTE = Column(String(100))
    ACQ_DISPOSED = Column(String(1))
    SHARE_VALUE = Column(String(30))
    SHAREVALUE_FTNOTE = Column(String(100))
    SHARES_AFTER = Column(String(30))
    SHAREAFT_FTNOTE = Column(String(100))
    OWNERSHIPTYPE = Column(String(1))
    OWNSHIP_FTNOTE = Column(String(100))
    INDBENF_OWNER = Column(String(100))
    INDBENF_OWNER_FTNOTE = Column(String(100))



class ZSECFORM5_FTNOTE(Base):
    __tablename__ = 'ZSECFORM5_FTNOTE'
    __table_args__ = (PrimaryKeyConstraint('ACCESSIONNO', 'FOOTNOTE_ID'),)

    MANDT = Column(String(3))
    ACCESSIONNO = Column(String(20))
    SEC_DOC = Column(String(40))
    FOOTNOTE_ID = Column(String(5))
    FOOTNOTE_TXT = Column(String)