# rx_dict = {
# 	'ZACCESSIONNO': re.compile(r'ACCESSION NUMBER:\t{2}(?P<accession_no>.*)'),
#     'ZSECDOC': re.compile(r'<SEC-DOCUMENT>(?P<sec_doc>.*)'),
#     'ZSEC_ACCEPTTIME': re.compile(r'<ACCEPTANCE-DATETIME>(?P<sec_acceptime>.*)'),
#     'ZCIK_ISSUER': re.compile(r'\t{2}CENTRAL INDEX KEY:\t{3}(?P<cik>.*)'),
#     'ZFORM_TYPE': re.compile(r'CONFORMED SUBMISSION TYPE:\t(?P<form_type>.*)'),
#     'ZSECHEADER': re.compile(r'<SEC-HEADER>(?P<sec_header>.*)'),
#     'ZDOC_COUNT': re.compile(r'PUBLIC DOCUMENT COUNT:\t{2}(?P<doc_count>.*)'),
#     'ZREPORT_PERIOD': re.compile(r'CONFORMED PERIOD OF REPORT:\t(?P<report_period>.*)'),
#     'ZDATE_FILED': re.compile(r'FILED AS OF DATE:\t{2}(?P<filed_date>.*)'),
#     'ZDATE_CHANGED': re.compile(r'DATE AS OF CHANGE:\t{2}(?P<change_date>.*)'),
#     'ZSEC_FILENO': re.compile(r'\t{2}SEC FILE NUMBER:\t{2}(?P<file_no>.*)'),
#     'ZXML_VERSION': re.compile(r'<\?xml version="(?P<xml_version>.*)" encoding="UTF-8"\?>'),
#     'ZSIGN_TITLE': re.compile(r'[ ]{6}<title>(?P<sign_title>.*)</title>'),
#     'ZSIGN_NAME': re.compile(r'[ ]{6}<name>(?P<sign_name>.*)</name>'),
#     'ZSIGN_DATE': re.compile(r'[ ]{6}<signatureDate>(?P<sign_date>.*)</signatureDate>'),
#     'ZTOTAL_TABENTRY': re.compile(r'[ ]{6}<tableEntryTotal>(?P<total_tab_entry>.*)</tableEntryTotal>'),
#     'ZTOTAL_TABVALUE': re.compile(r'[ ]{6}<tableValueTotal>(?P<total_tab_value>.*)</tableValueTotal>'),
#     'ZCOMPCONFDNAME': re.compile(r'\t{2}COMPANY CONFORMED NAME:\t{3}(?P<comp_name>.*)'),
#     'ZSEC_IRSNO': re.compile(r'\t{2}IRS NUMBER:\t{4}(?P<irs_no>.*)'),
#     'ZINCORP_STATE': re.compile(r'\t{2}STATE OF INCORPORATION:\t{3}(?P<inc_state>.*)'),
#     'ZFISCAL_YREND': re.compile(r'\t{2}FISCAL YEAR END:\t{3}(?P<fiscal_year>.*)'),
#     'BUS_ADDR': re.compile(r'\tBUSINESS ADDRESS:\t{0,1}'),
#     'MAIL_ADDR': re.compile(r'\tMAIL ADDRESS:\t{0,1}'), 
#     'STREET1': re.compile(r'\t{2}STREET 1:\t{2}(?P<street>.*)'),
#     'STREET2': re.compile(r'\t{2}STREET 2:\t{2}(?P<street>.*)'),
#     'CITY': re.compile(r'\t{2}CITY:\t{3}(?P<city>.*)'),
#     'REGION': re.compile(r'\t{2}STATE:\t{3}(?P<region>.*)'),
#     'POST_CODE': re.compile(r'\t{2}ZIP:\t{3}(?P<post_code>.*)'),
#     'ZBUS_TELF': re.compile(r'\t{2}BUSINESS PHONE:\t{2}(?P<bus_telf>.*)'),
# }

# rx_dict = {
# 	'ZACCESSIONNO': re.compile(r'ACCESSION NUMBER:\t{2}(?P<accession_no>[\d-]*)'),
#     'ZSECDOC': re.compile(r'<SEC-DOCUMENT>(?P<sec_doc>[-\w :]*)'),
#     'ZSEC_ACCEPTTIME': re.compile(r'<ACCEPTANCE-DATETIME>(?P<sec_acceptime>\d*)'),
#     'ZCIK_ISSUER': re.compile(r'\t{2}CENTRAL INDEX KEY:\t{3}(?P<cik>\d*)'),
#     'ZFORM_TYPE': re.compile(r'CONFORMED SUBMISSION TYPE:\t(?P<form_type>[-\w /]*)'),
#     'ZSECHEADER': re.compile(r'<SEC-HEADER>(?P<sec_header>[-\w :]*)'),
#     'ZDOC_COUNT': re.compile(r'PUBLIC DOCUMENT COUNT:\t{2}(?P<doc_count>\d*)'),
#     'ZREPORT_PERIOD': re.compile(r'CONFORMED PERIOD OF REPORT:\t(?P<report_period>\d*)'),
#     'ZDATE_FILED': re.compile(r'FILED AS OF DATE:\t{2}(?P<filed_date>\d*)'),
#     'ZDATE_CHANGED': re.compile(r'DATE AS OF CHANGE:\t{2}(?P<change_date>\d*)'),
#     'ZSEC_FILENO': re.compile(r'\t{2}SEC FILE NUMBER:\t(?P<file_no>[\d-]*)'),
#     'ZXML_VERSION': re.compile(r'<\?xml version="(?P<xml_version>[\d.]*)" encoding="UTF-8"\?>'),
#     'ZSIGN_TITLE': re.compile(r'[ ]{6}<title>(?P<sign_title>[\w, ]*)</title>'),
#     'ZSIGN_NAME': re.compile(r'[ ]{6}<name>(?P<sign_name>[\w, ]*)</name>'),
#     'ZSIGN_DATE': re.compile(r'[ ]{6}<signatureDate>(?P<sign_date>[\d-]*)</signatureDate>'),
#     'ZTOTAL_TABENTRY': re.compile(r'[ ]{6}<tableEntryTotal>(?P<total_tab_entry>\d*)</tableEntryTotal>'),
#     'ZTOTAL_TABVALUE': re.compile(r'[ ]{6}<tableValueTotal>(?P<total_tab_value>\d*)</tableValueTotal>'),
#     'ZCOMPCONFDNAME': re.compile(r'\t{2}COMPANY CONFORMED NAME:\t{3}(?P<comp_name>[\w, ]*)'),
#     'ZSEC_IRSNO': re.compile(r'\t{2}IRS NUMBER:\t{4}(?P<irs_no>\d*)'),
#     'ZINCORP_STATE': re.compile(r'\t{2}STATE OF INCORPORATION:\t{3}(?P<inc_state>[A-Z]*)'),
#     'ZFISCAL_YREND': re.compile(r'\t{2}FISCAL YEAR END:\t{2}(?P<fiscal_year>\d*)'),
#     'BUS_ADDR': re.compile(r'\tBUSINESS ADDRESS:\t'),
#     'MAIL_ADDR': re.compile(r'\tMAIL ADDRESS:\t'), 
#     'STREET1': re.compile(r'\t{2}STREET 1:\t{2}(?P<street>[\w, ]*)'),
#     'STREET2': re.compile(r'\t{2}STREET 2:\t{2}(?P<street>[\w, ]*)'),
#     'CITY': re.compile(r'\t{2}CITY:\t{3}(?P<city>[\w, ]*)'),
#     'REGION': re.compile(r'\t{2}STATE:\t{3}(?P<region>[\w, ]*)'),
#     'POST_CODE': re.compile(r'\t{2}ZIP:\t{3}(?P<post_code>\d*)'),
#     'ZBUS_TELF': re.compile(r'\t{2}BUSINESS PHONE:\t{2}(?P<bus_telf>\d*)'),
# }


